### ISSUE TITLE
Questions about the shiny dataset

### ISSUE THREAD

**Issue by 1zgh** [facebookresearch/hyperreel#12]
Are there complete CD data sets in shiny? I downloaded the CD data set according to the URL you provided, and used img2pose to get pose_bounds.npy, but when I run it, I get the message that hwf_cxcy.npy is missing. Do you have the script that generated this file to share? Thanks!!!

**Comment by breuckelen** [comment]
Hmm, that file should be available in the one drive folder that I linked in the README. I can see it here, for example: https://vistec-my.sharepoint.com/personal/pakkapon_p_s19_vistec_ac_th/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fpakkapon%5Fp%5Fs19%5Fvistec%5Fac%5Fth%2FDocuments%2Fpublic%2FVLL%2FNeX%2Fshiny%5Fdatasets%2Fshiny%2Fcd

**Comment by 1zgh** [comment]
Thanks!!!
