### ISSUE TITLE
Can not run for immersive dataset

### ISSUE THREAD

**Issue by qingxu-thu** [facebookresearch/hyperreel#13]
I try to run the immersive dataset Welder but after I prepare the environment with conda and CUDA 11.8, I get the error "RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)" I show the figures
![微信截图_20230207211332](https://user-images.githubusercontent.com/71426447/217254477-8afd5964-9691-4d4e-a45e-a5007df35e3b.png)

**Comment by breuckelen** [comment]
I ran into this issue at some point as well, and I think the fix was include `LD_LIBRARY_PATH=""' before each of the script calls. Let me know if this works.

**Comment by qingxu-thu** [comment]
Thanks very much, it works for me
