### ISSUE TITLE
How to start training?

### ISSUE THREAD

**Issue by geekdreamer04** [facebookresearch/hyperreel#16]
I have downloaded to 05_Horse mp.4 data from the google immersive website. I am completely new to this. I downloaded the data & put it in ~/data folde ras mentioned and tried to launch the training using the following command:
**"bash scripts/run_one_immersive.sh"** 

In the readme file, bash scripts/run_one_immersive.sh <gpu_to_use> <scene> <start_frame> this is the command. 
I am not sure what to fill in <gpu_to_use> <scene> and <start_frame> 
can you suggest me what an example input would look like?

I am running the model in a AWS EC2 g5.2xlarge server and used the env.yml file to setup my environment.
Looking forward to a quick response from you.

**Comment by geekdreamer04** [comment]
While i am just running, **"bash scripts/run_one_immersive.sh start_frame=10"**
I am getting the following error, which I am assuming is because i am not passing the launch command properly.

AttributeError: _evt
Error executing job with overrides: ['experiment/dataset=immersive', 'experiment/training=immersive_tensorf', 'experiment.training.val_every=5', 'experiment.training.test_every=10', 'experiment.training.ckpt_every=10', 'experiment.training.render_every=30', 'experiment.training.num_epochs=30', 'experiment/model=immersive_sphere', 'experiment.params.print_loss=True', 'experiment.dataset.collection=10', '+experiment/regularizers/tensorf=tv_4000', 'experiment.dataset.start_frame=', 'experiment.params.name=immersive_10_start_']
Traceback (most recent call last):
  File "main.py", line 209, in main
    elastic_run(cfg)
  File "main.py", line 204, in elastic_run
    run(cfg, "", "", "")
  File "main.py", line 98, in run
    dm.prepare_data()
  File "/home/ubuntu/hyperreel/nlf/__init__.py", line 148, in prepare_data
    self.reload_data()
  File "/home/ubuntu/hyperreel/nlf/__init__.py", line 154, in reload_data
    self.train_dataset = dataset_cl(self.cfg, split='train')
  File "/home/ubuntu/hyperreel/datasets/immersive.py", line 75, in __init__
    super().__init__(cfg, split, **kwargs)
  File "/home/ubuntu/hyperreel/datasets/base.py", line 531, in __init__
    super().__init__(cfg, split, **kwargs)
  File "/home/ubuntu/hyperreel/datasets/base.py", line 446, in __init__
    super().__init__(cfg, split, **kwargs)
  File "/home/ubuntu/hyperreel/datasets/base.py", line 106, in __init__
    self.prepare_data()
  File "/home/ubuntu/hyperreel/datasets/base.py", line 155, in prepare_data
    self.read_meta()
  File "/home/ubuntu/hyperreel/datasets/immersive.py", line 81, in read_meta
    with self.pmgr.open(os.path.join(self.root_dir, "models.json"), "r") as f:
  File "/home/ubuntu/anaconda3/envs/hyperreel/lib/python3.8/site-packages/iopath/common/file_io.py", line 1023, in open
    bret = handler._open(path, mode, buffering=buffering, **kwargs)  # type: ignore
  File "/home/ubuntu/anaconda3/envs/hyperreel/lib/python3.8/site-packages/iopath/common/file_io.py", line 611, in _open
    return open(  # type: ignore
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/data/hyperreel/immersive/05_Horse/10/models.json'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by breuckelen** [comment]
Hi! Both <gpu_to_use> and <start_frame> should just be numbers -- the first corresponding to the GPU ID (which depends on how many GPUs your machine has), and the second corresponding to the video frame you want to start training the model at (depends on how many frames are in the video sequence, which I believe is 300 for the Horse sequence). You also need to include the name of the scene. As an example, you can invoke the script with:

`bash scripts/run_one_immersive.sh 0 05_Horse 0`

which will train a model on the horse sequence, starting at frame 0, and using the GPU with ID 0.
