### ISSUE TITLE
How to run on RTX4090?

### ISSUE THREAD

**Issue by LRLVEC** [facebookresearch/hyperreel#2]
After conda env create, I ran with n3d dataset, then:
```
nvrtc: error: invalid value for --gpu-architecture (-arch)
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
I believe this is because cuda compute capability 8.9 is too new for pytorch or other libs.

**Comment by LRLVEC** [comment]
After switching to pytorch-nightly, I solved this problem.
environment.yml is like this:
```
name: hyperreel
channels:
  - pyg
  - pytorch-nightly
  - pytorch3d
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - cudatoolkit=11.6
  - cudatoolkit-dev
  - kornia
  - matplotlib
  - pillow
  - python=3.8
  - pip
  - pytorch3d
  - setuptools=59.5.0
  - pytorch
  - pytorch-lightning=1.7.6
  - scikit-image
  - scipy
  - torchvision
  - pip:
    - dearpygui
    - hydra-core==1.1.1
    - imageio
    - iopath==0.1.9
    - lpips==0.1.4
    - omegaconf==2.1.1
    - opencv-python
    - plyfile
    - gdown
```

**Comment by ZkzMMDC** [comment]
Hello, it seems that the CUDA 11.6 version cannot correspond to the torch 2.0.1 version corresponding to the 4090. How should this be solved?

**Comment by benattal** [comment]
Have you tried either using a newer version of cudatoolkit version or an older version of pytorch?
