### ISSUE TITLE
Questions about the Eikonal dataset

### ISSUE THREAD

**Issue by Yubel426** [facebookresearch/hyperreel#21]
Great work! I noticed that there is a dataset/eikonal.yaml file in the repository, but the training config files or script for eikonal are not provided. Have you tested it on this dataset? Can you provide the training config? The results I trained look very bad.

**Comment by benattal** [comment]
Hi! Several months ago I'd tried to use the dataset from Eikonal fields -- as mentioned in previous issues (and in the paper), HyperReel tends to struggle when the camera captures have relatively sparse coverage of the scene. This is the case for many *inward-facing* 360 degree datasets, for example, where the angular density of training rays is low compared to forward-facing scenes. 

With some hyper-parameter tuning, or different intersection functions, you may or may not get better performance on the Eikonal fields dataset. 

Hope this was helpful,
~Ben

**Comment by Yubel426** [comment]
@breuckelen Hi, thanks for your answer. I tried to replicate the Tarot Cards (large angular extent) in stanford dataset, but I still can't get results as good as the ones shown on your project homepage. I think the `run_one_stanford_llff_ndc.sh` script should be used for this scene. I would like to know if I need to modify any other parameters such as `experiment/dataset` or `experiment/training`.

Thank you again for your reply and answers.
![0002_pred](https://github.com/facebookresearch/hyperreel/assets/45202218/35ffb061-f5d6-4b1b-9a07-a35effd8b23d)

**Comment by benattal** [comment]
Would you mind sharing the command that you used to produce these results? If I run `bash scripts/run_one_stanford_llff_ndc.sh 1 tarot 1` then I get results that look like this


https://github.com/facebookresearch/hyperreel/assets/2993881/9b8f214d-8819-47d1-b022-c6916984465a

**Comment by Yubel426** [comment]
Thank you for your response. I will close this issue.
