### ISSUE TITLE
About the Sample Prediction Network of Dynamic scene

### ISSUE THREAD

**Issue by wangyuyy** [facebookresearch/hyperreel#24]
Hi Ben,
Thanks for sharing your great work!
Upon my investigation, I discovered that the input for the Sample Prediction Network, implemented through RayPredictionEmbedding, solely focuses on the information of rays and omits the inclusion of time. I am interested to know the rationale behind this exclusion. Could it be possible that I have misinterpreted the code?
The code I referred to is provided below. In the model configuration file I referenced, namely immersive_z_plane.yaml, the parameter param_channels was set as [(0, 6)], indicating the absence of time information.
https://github.com/facebookresearch/hyperreel/blob/20d4befda57611f7a3ab6e4e286a14feab30085d/nlf/embedding/ray.py#L316C1-L324C45

**Comment by benattal** [comment]
Hi, thanks for your question! I believe we only used the immersive_z_plane config to test on a single frame from the immersive sequences. The immersive_sphere configs include time: https://github.com/facebookresearch/hyperreel/blob/main/conf/experiment/model/immersive_sphere.yaml#L41

Best,
~Ben
