### ISSUE TITLE
Application of Datasets for 360 ° Scene

### ISSUE THREAD

**Issue by dzls952402394** [facebookresearch/hyperreel#29]
It's a great work!

I have a question about the application of Datasets for 360 ° Scene. 

Your work use Plucker parameterization. 

I have seen your website, but I don't see any 360° scene. 

Is there any difficulty in rendering 360 ° scene data?

**Comment by benattal** [comment]
Hey! We show some results in the paper on outward facing hemispherical captures (the Immersive Light Field Video dataset), and one result in the supplement on a 360 outward facing capture. These datasets have a relatively small baseline between input images --- even though we use the Plucker parameterization, our method tends to struggle with large baseline captures, for example inward-facing or object centric 360 degree captures.

It may be possible to improve performance, to some degree, by increasing the number of points that the ray-conditioned sample network predicts, at the cost of increased runtime. 

Hope this helps!

**Comment by dzls952402394** [comment]
I have seen the result of 360 degree Fov in your supplement, and thanks for your reply!
