### ISSUE TITLE
How did you obtain near and far values for technicolor/interdigital dataset

### ISSUE THREAD

**Issue by NagabhushanSN95** [facebookresearch/hyperreel#31]
Hi, 
When loading technicolor dataset, you have hard-coded the near and far values [here](https://github.com/facebookresearch/hyperreel/blob/main/datasets/technicolor.py#L126--L153). How did you obtain these bounds?

**Comment by benattal** [comment]
Apologies for the late response! They were determined experimentally (through trial and error).

**Comment by NagabhushanSN95** [comment]
Okay. Thank you!
