### ISSUE TITLE
How can I save the rendering video

### ISSUE THREAD

**Issue by ZhenyanSun** [facebookresearch/hyperreel#6]
Dear team, 
I can not launch gui from remote by ssh, so I want to save the rendered video into folder to check. Could you give me some instructions. Thanks very much.

**Comment by breuckelen** [comment]
During training a video should be written to an experiment folder in `~/logs`. Specifically, check out the `val_videos` directory in this experiment folder. For example `~/logs/donerf_barbershop_sphere/val_videos/20/rgb`

**Comment by geekdreamer04** [comment]
Hello,

I could perform training only when i set num_frames= 15 & load_full_step: 16
subsample_keyframe_step: 4
subsample_keyframe_frac: 0.25
subsample_frac: 0.0336

After training the model at this, I wanted to check the results in the logs folder. I see only 3 .png images in the folder. Can you explain why only 3 images are available?

**Comment by geekdreamer04** [comment]
Also, is there a way to launch the GUI from my remote environment?
